[[headers]]
  for = "/*"
  [headers.values]
    # iFrame-Einbettung von Systeme.io erlauben
    X-Frame-Options = "ALLOW-FROM https://drumlion.com"
    Content-Security-Policy = "frame-ancestors 'self' https://drumlion.com https://*.systeme.io https://*.systemeio.com"
    X-Content-Type-Options = "nosniff"
